#!/bin/bash
# OnePred Full History GRPO training script (standard single-turn GRPO)
# Usage: bash scripts/run_grpo_fullhistory.sh
#
# Core design:
#   - All conversation history is concatenated into one prompt, model directly outputs prediction
#   - Uses verl standard single-turn GRPO (verl.trainer.main_ppo)
#   - No agent loop / multi-turn interaction needed
#   - Uses the same reward (LLM Judge) and hyperparameters as agentic training

set -eo pipefail

# ============ Activate conda environment ============
eval "$(conda shell.bash hook)"
conda activate onepred
export PATH="${CONDA_PREFIX}/bin:${PATH}"

# ============ vLLM V1 engine ============
export VLLM_USE_V1=1

# ============ Reranker scoring model ============
export RERANKER_MODEL_PATH="${MODEL_DIR}/hf/Qwen3-Reranker-0.6B"
export RERANKER_DEVICE="cuda:0"

# ============ Pointwise Reward ============
# Listwise not enabled; using standard pointwise LLM Judge

# ============ WandB configuration ============
export WANDB_API_KEY="${WANDB_API_KEY}"

# ============ Path configuration ============
export PROJECT_DIR="${ONEPRED_ROOT}"
export VERL_DIR="${ONEPRED_ROOT}/third_party/verl"

# Model (supports external override, default Qwen3-8B)
export MODEL_PATH="${MODEL_PATH:-${MODEL_DIR}/hf/Qwen3-8B}"

# Full History RL data (generated by build_verl_rl_fullhistory.py)
export TRAIN_FILE="${TRAIN_FILE:-${PROJECT_DIR}/data/rl_fullhistory_train.parquet}"
export VAL_FILE="${VAL_FILE:-${PROJECT_DIR}/data/rl_fullhistory_val.parquet}"

# Custom reward function (same as agentic)
export REWARD_FN_PATH="${PROJECT_DIR}/onepred/reward_fn.py"

# Experiment directory
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
MODEL_NAME=$(basename "${MODEL_PATH}" | tr '[:upper:]' '[:lower:]')
export EXP_NAME="grpo-fullhistory-${MODEL_NAME}-${TIMESTAMP}"
export CKPT_DIR="${PROJECT_DIR}/checkpoints/${EXP_NAME}"
export LOG_FILE="${PROJECT_DIR}/logs/${EXP_NAME}.log"

mkdir -p "${PROJECT_DIR}/logs"
mkdir -p "${CKPT_DIR}"

# ============ Trajectory data saving ============
export ROLLOUT_DATA_DIR="${PROJECT_DIR}/rollout_traces/${EXP_NAME}/train"
export VAL_DATA_DIR="${PROJECT_DIR}/rollout_traces/${EXP_NAME}/val"
mkdir -p "${ROLLOUT_DATA_DIR}"
mkdir -p "${VAL_DATA_DIR}"

# ============ Training configuration (consistent with agentic) ============
NUM_GPUS=8
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-32}
ROLLOUT_N=${ROLLOUT_N:-8}
MAX_PROMPT_LENGTH=8192        # Full History prompt P99~4963 chars, max=9559 chars
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-3072}
LR=${LR:-1e-6}
TOTAL_EPOCHS=1
MICRO_BATCH=${MICRO_BATCH:-2}
TP=${TP:-2}
GPU_MEM_UTIL=${GPU_MEM_UTIL:-0.7}

# ============ Ensure scripts can be imported ============
export PYTHONPATH="${PROJECT_DIR}:${PYTHONPATH}"

# ============ Start training ============
export PYTHONUNBUFFERED=1

echo "=========================================="
echo "Full History GRPO Training (standard single-turn)"
echo "Experiment name: ${EXP_NAME}"
echo "Model path: ${MODEL_PATH}"
echo "Training data: ${TRAIN_FILE}"
echo "Validation data: ${VAL_FILE}"
echo "Checkpoint directory: ${CKPT_DIR}"
echo "Log file: ${LOG_FILE}"
echo "=========================================="

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=${TRAIN_FILE} \
    data.val_files=${VAL_FILE} \
    data.train_batch_size=${TRAIN_BATCH_SIZE} \
    data.max_prompt_length=${MAX_PROMPT_LENGTH} \
    data.max_response_length=${MAX_RESPONSE_LENGTH} \
    data.filter_overlong_prompts=True \
    data.truncation=error \
    data.return_raw_chat=True \
    +data.apply_chat_template_kwargs.enable_thinking=True \
    actor_rollout_ref.model.path=${MODEL_PATH} \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=${LR} \
    actor_rollout_ref.actor.optim.lr_scheduler_type=cosine \
    actor_rollout_ref.actor.optim.min_lr_ratio=0.1 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.02 \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${MICRO_BATCH} \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${TP} \
    actor_rollout_ref.rollout.gpu_memory_utilization=${GPU_MEM_UTIL} \
    actor_rollout_ref.rollout.n=${ROLLOUT_N} \
    actor_rollout_ref.rollout.enforce_eager=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=${MICRO_BATCH} \
    actor_rollout_ref.rollout.logprobs_mode=null \
    actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=4096 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=${MICRO_BATCH} \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    reward.custom_reward_function.path=${REWARD_FN_PATH} \
    reward.custom_reward_function.name=compute_score \
    trainer.critic_warmup=0 \
    trainer.balance_batch=False \
    trainer.logger='["console","wandb"]' \
    trainer.project_name=OnePred \
    trainer.experiment_name=${EXP_NAME} \
    trainer.n_gpus_per_node=${NUM_GPUS} \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.total_epochs=${TOTAL_EPOCHS} \
    trainer.default_local_dir=${CKPT_DIR} \
    trainer.rollout_data_dir=${ROLLOUT_DATA_DIR} \
    trainer.validation_data_dir=${VAL_DATA_DIR} \
    trainer.log_val_generations=20 \
    trainer.resume_mode=${RESUME_MODE:-disable} \
    trainer.resume_from_path=${RESUME_PATH:-null} \
    2>&1 | tee ${LOG_FILE}

echo "Training complete, log saved at: ${LOG_FILE}"
