#!/bin/bash
# OnePred Agentic GRPO training script (Approach B: independent training per turn)
# Usage: bash scripts/run_grpo_agentic.sh
#
# Approach B core design:
#   - Each turn is treated as an independent (prompt, response) training sample
#   - During training, the model only sees that turn's fresh prompt (system + memory + observation)
#   - All turns in the same trajectory share the final turn's scalar reward
#   - Uses custom RecurrentAgentLoopManager to expand each turn into independent batch rows
#   - Uses custom RecurrentRayPPOTrainer to handle 1D GRPO advantage

set -eo pipefail

# ============ Activate conda environment ============
eval "$(conda shell.bash hook)"
conda activate onepred
# Ensure conda env bin is at the front of PATH (in tmux etc., system path may precede conda)
export PATH="${CONDA_PREFIX}/bin:${PATH}"

# ============ vLLM V1 engine ============
export VLLM_USE_V1=1

# ============ Reranker scoring model ============
export RERANKER_MODEL_PATH="${MODEL_DIR}/hf/Qwen3-Reranker-0.6B"
export RERANKER_DEVICE="cuda:0"

# ============ Pointwise Reward ============
# Listwise not enabled; using standard pointwise LLM Judge
# export USE_LISTWISE_REWARD=1

# ============ Format Reward weight ============
# During training, mix format reward: reward = 0.9 * judge + 0.1 * format
# During evaluation, this variable is not set (default 0), using pure judge reward
export ONEPRED_FORMAT_REWARD_WEIGHT="${ONEPRED_FORMAT_REWARD_WEIGHT:-0.1}"

# ============ WandB configuration ============
export WANDB_API_KEY="${WANDB_API_KEY}"

# ============ Path configuration ============
export PROJECT_DIR="${ONEPRED_ROOT}"
export VERL_DIR="${ONEPRED_ROOT}/third_party/verl"

# SFT checkpoint (HF format)
export MODEL_PATH="${MODEL_PATH:-${ONEPRED_ROOT}/checkpoints/grpo-fullhistory-qwen3-8b-20260417_001551/global_step_500/merged_hf}"

# Agentic RL data (generated by build_verl_rl_agentic.py)
export TRAIN_FILE="${TRAIN_FILE:-${PROJECT_DIR}/data/rl_agentic_train.parquet}"
export VAL_FILE="${VAL_FILE:-${PROJECT_DIR}/data/rl_agentic_val.parquet}"

# Custom reward function
export REWARD_FN_PATH="${PROJECT_DIR}/onepred/reward_fn.py"

# Interaction configuration
export INTERACTION_CONFIG="${PROJECT_DIR}/configs/interaction_config.yaml"

# Agent loop configuration
export AGENT_LOOP_CONFIG="${PROJECT_DIR}/configs/recurrent_agent_loop_config.yaml"

# Experiment directory
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
MODEL_NAME=$(basename "${MODEL_PATH}" | tr '[:upper:]' '[:lower:]')
# If MODEL_PATH ends with merged_hf, go up to get the model name
if [ "${MODEL_NAME}" = "merged_hf" ]; then
    MODEL_NAME=$(basename "$(dirname "$(dirname "${MODEL_PATH}")")" | sed 's/grpo-fullhistory-//' | sed 's/-20.*//')
fi
export EXP_NAME="grpo-agentic-${MODEL_NAME}-${TIMESTAMP}"
export CKPT_DIR="${PROJECT_DIR}/checkpoints/${EXP_NAME}"
export LOG_FILE="${PROJECT_DIR}/logs/${EXP_NAME}.log"

mkdir -p "${PROJECT_DIR}/logs"
mkdir -p "${CKPT_DIR}"

# ============ Trajectory data saving ============
# verl native dump (flat input/output)
export ROLLOUT_DATA_DIR="${PROJECT_DIR}/rollout_traces/${EXP_NAME}/train"
export VAL_DATA_DIR="${PROJECT_DIR}/rollout_traces/${EXP_NAME}/val"
mkdir -p "${ROLLOUT_DATA_DIR}"
mkdir -p "${VAL_DATA_DIR}"

# OnePred structured traces (per-turn observation -> model_response)
export ONEPRED_TRACE_DIR="${PROJECT_DIR}/rollout_traces/${EXP_NAME}/structured"
mkdir -p "${ONEPRED_TRACE_DIR}"

# ============ Training configuration ============
NUM_GPUS=8
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-32}
ROLLOUT_N=${ROLLOUT_N:-8}
MAX_PROMPT_LENGTH=8192        # Larger space needed without response truncation (P99~5400 tokens, max~9600)
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-4096}
LR=${LR:-5e-7}
TOTAL_EPOCHS=1
MICRO_BATCH=${MICRO_BATCH:-2}
TP=${TP:-2}
GPU_MEM_UTIL=${GPU_MEM_UTIL:-0.7}

# ============ Ensure scripts can be imported ============
export PYTHONPATH="${PROJECT_DIR}:${PYTHONPATH}"

# ============ Start training ============
export PYTHONUNBUFFERED=1

echo "=========================================="
echo "Agentic GRPO Training"
echo "Experiment name: ${EXP_NAME}"
echo "Model path: ${MODEL_PATH}"
echo "Training data: ${TRAIN_FILE}"
echo "Interaction: ${INTERACTION_CONFIG}"
echo "Agent Loop Config: ${AGENT_LOOP_CONFIG}"
echo "Checkpoint directory: ${CKPT_DIR}"
echo "Log file: ${LOG_FILE}"
echo "Training traces saved to: ${ROLLOUT_DATA_DIR}"
echo "Validation traces saved to: ${VAL_DATA_DIR}"
echo "Structured traces: ${ONEPRED_TRACE_DIR}"
echo "=========================================="

python3 -m onepred.main_ppo_recurrent \
    algorithm.adv_estimator=grpo \
    data.train_files=${TRAIN_FILE} \
    data.val_files=${VAL_FILE} \
    data.train_batch_size=${TRAIN_BATCH_SIZE} \
    data.max_prompt_length=${MAX_PROMPT_LENGTH} \
    data.max_response_length=${MAX_RESPONSE_LENGTH} \
    data.filter_overlong_prompts=True \
    data.truncation=error \
    data.return_raw_chat=True \
    +data.apply_chat_template_kwargs.enable_thinking=True \
    actor_rollout_ref.model.path=${MODEL_PATH} \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=${LR} \
    actor_rollout_ref.actor.optim.lr_scheduler_type=cosine \
    actor_rollout_ref.actor.optim.min_lr_ratio=0.1 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.02 \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${MICRO_BATCH} \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=${KL_LOSS_COEF:-0} \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=${ENTROPY_COEFF:-0} \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${TP} \
    actor_rollout_ref.rollout.gpu_memory_utilization=${GPU_MEM_UTIL} \
    actor_rollout_ref.rollout.n=${ROLLOUT_N} \
    actor_rollout_ref.rollout.enforce_eager=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=${MICRO_BATCH} \
    actor_rollout_ref.rollout.logprobs_mode=null \
    actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=4096 \
    actor_rollout_ref.rollout.multi_turn.enable=True \
    actor_rollout_ref.rollout.multi_turn.max_assistant_turns=20 \
    actor_rollout_ref.rollout.multi_turn.max_user_turns=20 \
    actor_rollout_ref.rollout.multi_turn.interaction_config_path=${INTERACTION_CONFIG} \
    actor_rollout_ref.rollout.multi_turn.format=hermes \
    actor_rollout_ref.rollout.agent.default_agent_loop=recurrent_memory_agent \
    +actor_rollout_ref.rollout.agent.agent_loop_config_path=${AGENT_LOOP_CONFIG} \
    +actor_rollout_ref.rollout.agent.agent_loop_manager_class=onepred.recurrent_generation_manager.RecurrentAgentLoopManager \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    reward.custom_reward_function.path=${REWARD_FN_PATH} \
    reward.custom_reward_function.name=compute_score \
    trainer.critic_warmup=0 \
    trainer.balance_batch=False \
    trainer.logger='["console","wandb"]' \
    trainer.project_name=OnePred \
    trainer.experiment_name=${EXP_NAME} \
    trainer.n_gpus_per_node=${NUM_GPUS} \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.total_epochs=${TOTAL_EPOCHS} \
    trainer.default_local_dir=${CKPT_DIR} \
    trainer.rollout_data_dir=${ROLLOUT_DATA_DIR} \
    trainer.validation_data_dir=${VAL_DATA_DIR} \
    trainer.log_val_generations=20 \
    trainer.resume_mode=${RESUME_MODE:-disable} \
    trainer.resume_from_path=${RESUME_PATH:-null} \
    2>&1 | tee ${LOG_FILE}

echo "Training complete, log saved at: ${LOG_FILE}"
